version: 0.2
env:
  variables: 
     ECR_REGISTRY_URL: 424756289338.dkr.ecr.ap-southeast-1.amazonaws.com
     IMAGE_REPO_NAME: blog
     IMAGE_TAG: Latest
phases:
  
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin $ECR_REGISTRY_URL
      - REPOSITORY_URI=$ECR_REGISTRY_URL/$IMAGE_REPO_NAME:$IMAGE_TAG
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI -f Dockerfile .
      - 
post_build:
  commands:
    - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_REGISTRY_URL/$IMAGE_REPO_NAME:$IMAGE_TAG
